"""add details to projects

Revision ID: 60605c556bbd
Revises: f9a694f864d0
Create Date: 2025-06-25 20:43:22.259635

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "60605c556bbd"
down_revision: Union[str, Sequence[str], None] = "f9a694f864d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("live_site", sa.Boolean(), nullable=True))
    op.add_column(
        "projects",
        sa.Column("details", sa.String(length=800), server_default="", nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "details")
    op.drop_column("projects", "live_site")
    # ### end Alembic commands ###
